
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: laravel_app
    volumes:
      - ./public:/var/www/html/public
      - ./resources:/var/www/html/resources
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: laravel_node
    working_dir: /var/www/html
    volumes:
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public
    command: npm run dev
    ports:
      - "5173:5173"
    networks:
      - laravel_network

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html:ro
    depends_on:
      - app
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
    driver: bridge
